### ISSUE TITLE
We need to discuss about how to divide the time stage!

### ISSUE THREAD

**Issue by Rouwanzii** [Rouwanzii/Spiritualism-Newspaper---DS4D-2019#2]
I don't think it's a good idea to divide the data averagely into 4 parts. What do you think about to divide the data into 3 stages according to the newspaper number issued each year?

**Comment by patri45** [comment]
Ok, it's a good advice, I will consider it.
But It's kind of difficult, I'll try.

**Comment by yanghang226** [comment]
I agree that  we divide the time stage according to the issued number and can divide the stage of spiritualism movement into"developing, popular, and Fading"..

**Comment by Rouwanzii** [comment]
Great! Let's do it like this.
